version: '3.1'

services:
  db:
    container_name: devpass-mysql
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
  account-management:
    container_name: account-management-service
    image: michelfsilva/dev-pass-account-management:1.0.0
    restart: always
    ports:
      - '8081:8081'